In [38]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

## read data

In [39]:
site_df = pd.read_csv('/Users/mouyly/Downloads/jupiter_notebook/SCATS_cleaned.csv' , skiprows=9)
site_df.head()

,Site Number,Location Description,Site Type,Directory,Map reference,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,964,ABBOTTS/CLELANDS DEVELOPMENTS,INT,Melway,095G08,NaN,NaN,NaN,NaN
1,968,ABBOTTS/GAINE/MONASH,INT,Melway,095K08,NaN,NaN,NaN,NaN
2,972,ABBOTTS/NATIONAL,INT,Melway,95J08,NaN,NaN,NaN,NaN
3,983,ABBOTTS/REMINGTON,INT,Melway,095G08,NaN,NaN,NaN,NaN
4,1053,ABBOTTSFORD/HAINES,INT,Melway,2A-G07,NaN,NaN,NaN,NaN

In [40]:
# Drop columns that are completely empty (all NaN)
site_df = site_df.dropna(axis=1, how='all')

# Preview cleaned dataframe
site_df.head()

,Site Number,Location Description,Site Type,Directory,Map reference
0,964,ABBOTTS/CLELANDS DEVELOPMENTS,INT,Melway,095G08
1,968,ABBOTTS/GAINE/MONASH,INT,Melway,095K08
2,972,ABBOTTS/NATIONAL,INT,Melway,95J08
3,983,ABBOTTS/REMINGTON,INT,Melway,095G08
4,1053,ABBOTTSFORD/HAINES,INT,Melway,2A-G07

In [41]:
print(site_df.columns)

Index(['Site Number', 'Location Description', 'Site Type', 'Directory',
       'Map reference '],
      dtype='object')

## clean the data

### check for missing value

In [42]:
site_df.isnull().sum()

Site Number               0
Location Description      0
Site Type                 0
Directory               202
Map reference           341
dtype: int64

In [43]:
print(site_df.columns.tolist())

['Site Number', 'Location Description', 'Site Type', 'Directory', 'Map reference ']

### check for duplicated

In [44]:
site_df.duplicated(subset=['Site Number']).sum()

np.int64(290)

In [45]:
site_df[site_df['Site Number'].isnull()]

Empty DataFrame
Columns: [Site Number, Location Description, Site Type, Directory, Map reference ]
Index: []

In [46]:
# Remove duplicate site numbers, keeping the first occurrence
site_df = site_df.drop_duplicates(subset='Site Number', keep='first')

# Confirm it's done
print(f"Remaining rows after removing duplicates: {len(site_df)}")

Remaining rows after removing duplicates: 4225

## merging data

### with scats oct 2006

In [48]:
#import scats 
long_df = pd.read_csv('Cleaned_SCATS_Oct2006.csv')
#rename site number
site_df.rename(columns={'Site Number': 'Site ID'}, inplace=True)
#merge
merged_df = pd.merge(long_df, site_df, on='Site ID', how='left')
#result
print("Shape after merge:", merged_df.shape)
print("Missing values:\n", merged_df.isnull().sum())

Shape after merge: (381431, 11)
Missing values:
 Site ID                 0
Date                    0
Interval                0
Volume                  0
IntervalNum             0
Time                    0
Timestamp               0
Location Description    0
Site Type               0
Directory               0
Map reference           0
dtype: int64

In [49]:
#save
merged_df.to_csv("Merged_SCATS_with_SiteListing.csv", index=False)
print(" File saved as 'Merged_SCATS_with_SiteListing.csv'")

 File saved as 'Merged_SCATS_with_SiteListing.csv'

In [56]:
#load coordi
geo_df = pd.read_csv("Cleaned_SCATS_Oct2006_coord.csv")

# Merge location
final_df = pd.merge(merged_df, geo_df, on='Site ID', how='left')

# check for any unmatched coordinates
print("Missing after merge:\n", final_df[['Lat', 'Long']].isnull().sum())

Missing after merge:
 Lat     0
Long    0
dtype: int64
Saved: Final_SCATS_with_LatLong.csv

In [57]:
final_df[['Lat', 'Long']].isnull().sum()

Lat     0
Long    0
dtype: int64

In [58]:
final_df.duplicated().sum()
final_df.isnull().sum()

Site ID                 0
Date                    0
Interval                0
Volume                  0
IntervalNum             0
Time                    0
Timestamp               0
Location Description    0
Site Type               0
Directory               0
Map reference           0
Lat                     0
Long                    0
dtype: int64

In [ ]:
# Save 
final_df.to_csv("Final_SCATS_with_LatLong.csv", index=False)
print("Saved: Final_SCATS_with_LatLong.csv")